apiVersion: V1
kind: ReplicationController
metadata:
  name: replication
spec:
  replica: 4
  selector:
    app:my_app
  template:
    metadata:
      lables:
        app:my_app
  spec:
    container:
     - name: c01
       image: https
       ports:
        - ContainerPost: 80
