apiVersion: v1
kind: ReplicationController
metadata:
  name: podname
spec:
  replica: 4
  selector:
    app:my_app
  template:
    metadata:
    lables:
       app:my_app
  spec:
    containers:
     - name: c01
       image: httpd
       ports:
        - ContainerPort: 80

-------------------------------------------------------------------------------------------------
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
